### ISSUE TITLE
Authenticatie mislukt, basis authenticatie is uitgeschakeld (Nodemailer, Outlook)

### ISSUE THREAD

**Issue by Roland-1124997** [Rottie89132/PortFolio#1]
### Probleem Beschrijving
Authenticatie mislukt, basis authenticatie is uitgeschakeld. [AM4PR0302CA0001.eurprd03.prod.outlook.com 2024-10-07T08:59:48.012Z 08DCE50A0E939E00]

### Stappen om te Reproduceren
1. Probeer een e-mail te verzenden met de huidige configuratie in useMail.ts.
2. Observeer de authenticatiefout.

### Verwacht Gedrag
De e-mail zou succesvol moeten worden verzonden zonder authenticatiefouten.

### Actueel Gedrag
De e-mail kan niet worden verzonden met de foutmelding: "Authenticatie mislukt, basis authenticatie is uitgeschakeld."

### Aanvullende Informatie
- Bestand: \`useMail.ts\`
- E-mailprovider: Outlook
- E-mailbibliotheek: Nodemailer
- Foutmelding: Authenticatie mislukt, basis authenticatie is uitgeschakeld. [AM4PR0302CA0001.eurprd03.prod.outlook.com 2024-10-07T08:59:48.012Z 08DCE50A0E939E00]

**Comment by Rottie89132** [comment]
probleem opgelost door een gmail te gebruiken het enige negative is dat gmail veel langzamer is en tot 5 minuten kan duren

**Comment by Roland-1124997** [comment]
probleem opgelost door een gmail te gebruiken het enige negative is dat gmail veel langzamer is en tot 5 minuten kan duren
